### PR TITLE
Update picard docker

### PR DESCRIPTION
**Pull request by sickler-alex**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Update all picard tools to use the pgc-images.sbgenomics.com/d3b-bixu/picard:2.18.9R docker.

Fixes # https://app.zenhub.com/workspaces/d3b-bfx-5cdd720eed0dce4209e0b8a5/issues/d3b-center/bixu-tracker/1102

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] WGS runs [previous version](https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/ac6bd58a-f5a1-4c98-ba44-773d03d76ecb/), [test run with updated docker](https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/0300394a-9268-44c4-acf3-7604ce37c1c1/)
- [X] WXS runs [previous version](https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/59f2f9cf-470f-492a-b287-79f5f80de709/), [test run with updated docker](https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/6823b0aa-3944-473c-944d-c852ec15402d/)

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ X I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings
- [X] I have committed any related changes to the PR

### CODE REVIEW

**Comment by sickler-alex** [comment]
To compare the runs, I pulled the qc metrics for these runs and compared them. Attached is the excel file with the metrics and the comparison.
[metrics_comp.xlsx](https://github.com/kids-first/kf-alignment-workflow/files/6584942/metrics_comp.xlsx)

**Review by migbro — CHANGES_REQUESTED** [review]
Looks good! The comparison tests and sheets were quite helpful. One more thing to do would be to increment the release version for the main align wf AND the haplotype caller wf, as they both use the same sub wf that uses picard tools.

**Comment by sickler-alex** [comment]
@migbro did I miss a place for the version number? The last commit updates the link to the new tag that will get created once this is approved.

**Comment by migbro** [comment]
> @migbro did I miss a place for the version number? The last commit updates the link to the new tag that will get created once this is approved.

Ah, so I was referring to the github release version, sorry. So in the scripts `workflows/kfdrc_alignment_wf.cwl` and `workflows/kfdrc-gatk-haplotypecaller-wf.cwl`, these lines: 

```
- id: 'https://github.com/kids-first/kf-alignment-workflow/releases/tag/v2.7.0'
  label: github-release
```

```
- id: 'https://github.com/kids-first/kf-alignment-workflow/releases/tag/v2.6.0'
  label: github-release
```
Just increment increment each by 0.0.1 please. Thanks!

**Review by dmiller15 — APPROVED** [review]

**Review by migbro — APPROVED** [review]
Good catch on the versioning!

**Pull request merged**
