### PR TITLE
As qc wf

### PR DESCRIPTION
**Pull request by sickler-alex**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Changes to the FastQC workflow to fail the workflow if an input file fails in FastQC and calculate Q20 and Q30 on multiple input files.

Fixes # https://app.zenhub.com/workspaces/d3b-bfx-5cdd720eed0dce4209e0b8a5/issues/d3b-center/bixu-tracker/931

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] [Cavatica test using original inputs that failed](https://cavatica.sbgenomics.com/u/d3b-bixu/dev-sample-qc/tasks/61aa47a8-0468-49e4-9d4d-cd2d391f2401/)
- [X] [Cavatica test with multiple inputs](https://cavatica.sbgenomics.com/u/d3b-bixu/dev-sample-qc/tasks/9f3c07d3-0686-4cc6-a6eb-99c7f48442d5/)
- [X] [Cavatica test with our expected use case](https://cavatica.sbgenomics.com/u/d3b-bixu/dev-sample-qc/tasks/bb400dbb-7fdb-4209-90ab-786e806d8518/)

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings
- [X] I have committed any related changes to the PR

### CODE REVIEW

**Review by dmiller15 — COMMENTED** [review]
Do you have an example run of the pipeline failing due to the html count not matching the sequence count?

**Comment by sickler-alex** [comment]
The first test link failed because the one input file failed in FastQC. The job.err log file shows two errors while running FastQC and another one at the end saying that there was a problem when running FastQC which is expected. The first error is an error with the FastQC parameter file when reading the duplication error cut off. This error shouldn't be causing a problem when running FastQC since that module is turned off; but I'll update the parameter file in the project so it won't show up.

**Review by dmiller15 — APPROVED** [review]
Ok. That's what I was looking for. Must have missed it originally.

**Review by migbro — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
