### PR TITLE
🐳 dockerPull from new registry

### PR DESCRIPTION
**Pull request by dmiller15**
## Description

This PR updates the dockerPull statements to the new registry.
It also explicitly states shellquote for the rgstring in bwa-mem. This change counteracts an issue introduced by pushing with the new rabix composer.

Part of https://github.com/d3b-center/bixu-tracker/issues/846

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [x] WXS with Agg Metrics and gVCF creation: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/217ca7d6-d886-4257-8e13-df5dc11c847a/
- [x] HS Metrics pulls here but fails because we don't have the appropriate intervals: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/ce0437f5-4871-41ca-be2e-9735a0f7c37f/#
- [x] WGS BAM + WGS Metrics: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/f9cdea56-bbef-418d-8382-fed8d5d6b054/#
- [x] fastq_chomp is the only tool fastq processing not used in either of the above, so this test of the tool should cover FASTQ processing: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/92093e47-359a-42a1-acf7-37b3dc261837/#

**Test Configuration**:
* Environment: Cavatica
* Test files: see tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by migbro** [comment]
WXS failed from heap space - likely because WGS intervals used for HS metrics, otherwise it probably would have passed.

**Comment by dmiller15** [comment]
Yeah as long as the docker pulled I'm fine with HS Metrics failing. That test was still supposed to generate the gVCF so I'll take out HS Metrics for now just to see if the end of the pipeline is fine.

**Review by zhangb1 — APPROVED** [review]
checked all the tools under `kf-alignment-workflow/tools`  all the dockerPull has been using the SBG repo images.

except for the WXS metrics ,and tasks seems good

**Review by migbro — APPROVED** [review]
Given that all the tests pass now, I will pass this too

**Pull request merged**
